name: 🎉 Release My Testing Branch Binary

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with: 
          ref: testing
          fetch-depth: 1
      
      - name: "Set up Go"
        uses: actions/setup-go@v5
        with: 
          go-version: 1.21.x

      - name: "Get current date"
        id: get-date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v6
        with: 
          args: "release --rm-dist"
          version: latest
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GO_RELEASE_VERSION: "testing-${{ env.DATE }}"